(function(){
'use strict';
const MAX_BACKUP_BYTES=10*1024*1024;
const backupJSON=data=>JSON.stringify(data,null,2);
const backupSize=data=>new TextEncoder().encode(backupJSON(data)).byteLength;
const C=globalThis.TusCore, KEY='tus-yerel-prototype-v1', PREVIOUS=KEY+'-before-import';
const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toISOString(), uid=()=>globalThis.crypto?.randomUUID?.()||`e-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const kinds={recall:'Hatırlama',explain:'Açıklama',discriminate:'Ayırt etme'}, results={correct:'Doğru · öz değerlendirme',incorrect:'Eksik / yanlış · öz değerlendirme',unknown:'Bilmiyorum'};
const fictional=[
 ['demo-luma','Luma kuralını hatırlama','Kurgusal Luma istasyonuna yalnız mavi etiketli kapsüller alınır.','Mavi etiket','Luma istasyonuna hangi etiketli kapsüller alınır?','Mavi etiket, Luma girişinin tek koşuludur. Kapsülün boyutu bu kuralı değiştirmez.','Küçük kırmızı kapsül ve büyük mavi kapsül var. Hangisi Luma istasyonuna alınır?','Büyük mavi kapsül.'],
 ['demo-nera','Nera koşulunu açıklama','Kurgusal Nera kapısı, halka ve çizgi birlikte varsa açılır. Birinin bulunması yeterli değildir.','Halka ve çizgi birlikte','Nera kapısının açılması için hangi iki işaret birlikte bulunmalı?','İki koşul birlikte gerekli: yalnız halka ya da yalnız çizgi kapıyı açmaz.','Bir kartta yalnız halka, diğerinde halka ve çizgi var. Nera kapısını hangi kart açar?','Halka ve çizgi olan kart.'],
 ['demo-sera','Sera sırasını ayırt etme','Kurgusal Sera cihazı önce tarama, sonra eşleme yapar. Doğru sıra tarama → eşlemedir.','Önce tarama, sonra eşleme','Sera cihazının iki adımı hangi sırada çalışır?','Eşleme taramadan sonra gelir. Aynı iki adımın ters sırada olması kuralı karşılamaz.','A dizisi eşleme → tarama; B dizisi tarama → eşleme. Sera için hangisi doğru?','B dizisi: tarama → eşleme.']
];
const demoTasks=fictional.flatMap(([o,title,study,answer,prompt,explain,choice,choiceAnswer])=>[
 {id:o+'-r',objectiveId:o,objectiveTitle:title,familyId:o+'-family',kind:'recall',prompt,answer,explanation:study,hint:'Kısa kuralı ve belirleyici özelliğini düşün.',bank:'training',status:'synthetic',estimatedMinutes:2,version:1,source:'Kurgusal arayüz test verisi; tıbbi bilgi içermez.',reviewedAt:null},
 {id:o+'-e',objectiveId:o,objectiveTitle:title,familyId:o+'-family',kind:'explain',prompt:`Kuralın neden bu şekilde uygulandığını kendi cümlenle açıkla: ${study}`,answer:explain,explanation:study,hint:'Gerekli koşulu ve yetersiz kalan durumu ayır.',bank:'training',status:'synthetic',estimatedMinutes:3,version:1,source:'Kurgusal arayüz test verisi; tıbbi bilgi içermez.',reviewedAt:null},
 {id:o+'-d',objectiveId:o,objectiveTitle:title,familyId:o+'-family',kind:'discriminate',prompt:choice,answer:choiceAnswer,explanation:study,hint:'Yalnızca kuralın belirlediği özelliğe bak.',bank:'training',status:'synthetic',estimatedMinutes:2,version:1,source:'Kurgusal arayüz test verisi; tıbbi bilgi içermez.',reviewedAt:null}
]);
const empty=()=>({format:'tus-android-prototype',version:1,mode:'demo',demo:C.createState(),personal:C.createState(),tasks:[]});
let persistedRaw=null, writeAuthorized=false;
let app=empty(), writable=true, blocked=false, view='today', session=null, editing=false, deferredInstall=null;
const state=()=>app[app.mode==='demo'?'demo':'personal'];
const tasks=()=>app.mode==='demo'?demoTasks:app.tasks;
const coreTasks=(cat=tasks())=>cat.map(({id,objectiveId,familyId,kind,bank,status,estimatedMinutes,version})=>({id,objectiveId,familyId,kind,bank,status,estimatedMinutes,version}));
const makePlan=()=>C.plan(state(),coreTasks(),state().settings.minutes,now()).map(x=>({...x,task:tasks().find(t=>t.id===x.task.id)}));
const text=(v,max=20000)=>typeof v==='string'&&v.length>0&&v.length<=max;
function validateEnvelope(data){
 if(backupSize(data)>MAX_BACKUP_BYTES)throw Error('Yedek boyutu 10 MB sınırını aşıyor.');
 if(!data||typeof data!=='object'||Array.isArray(data)||Object.keys(data).sort().join(',')!=='demo,format,mode,personal,tasks,version'||data.format!=='tus-android-prototype'||data.version!==1||!['demo','personal'].includes(data.mode)||!Array.isArray(data.tasks)||data.tasks.length>2000)throw Error('Bu dosya desteklenen bir TUS yedeği değil.');
 C.validateState(data.demo);C.validateState(data.personal);
 C.validateTasks(coreTasks(data.tasks));
 const ids=new Set();
 for(const t of data.tasks){
  const expected=['id','objectiveId','objectiveTitle','familyId','kind','prompt','answer','explanation','hint','bank','status','estimatedMinutes','version','source','reviewedAt'].sort().join(',');
  if(!t||typeof t!=='object'||Object.keys(t).sort().join(',')!==expected||!['id','objectiveId','objectiveTitle','familyId','prompt','answer','source'].every(k=>text(t[k]))||typeof t.explanation!=='string'||t.explanation.length>20000||typeof t.hint!=='string'||t.hint.length>20000||!Object.hasOwn(kinds,t.kind)||t.bank!=='training'||t.status!=='approved'||t.version!==1||!Number.isInteger(t.estimatedMinutes)||t.estimatedMinutes<1||t.estimatedMinutes>30||!text(t.reviewedAt,40)||!Number.isFinite(Date.parse(t.reviewedAt))||ids.has(t.id)||t.id.startsWith('demo-'))throw Error('Yedekte geçersiz veya yinelenmiş soru var.');
  ids.add(t.id);
 }
 for(const [st,cat] of [[data.demo,demoTasks],[data.personal,data.tasks]]){
  const map=new Map(cat.map(t=>[t.id,t]));const objectives=new Set(cat.map(t=>t.objectiveId));
  for(const e of st.events){
   if(!objectives.has(e.objectiveId))throw Error('Kayıt, yedekte bulunmayan bir hedefe bağlı.');
   if(e.type==='external'){if(e.source!=='self_report')throw Error('Bu sürüm yalnız kişisel çalışma beyanını destekler.');continue;}
   if(e.taskId!==null){const t=map.get(e.taskId);if(!t||t.objectiveId!==e.objectiveId||t.familyId!==e.familyId||t.version!==e.taskVersion||(e.type==='attempt'&&(t.kind!==e.kind||t.bank!==e.bank)))throw Error('Soru ile çalışma kaydı birbiriyle eşleşmiyor.');}
  }
 }
 return data;
}
function notify(message){$('#notice').textContent=message;$('#notice').hidden=false;}
function save(next){
 if(!writeAuthorized){notify('Bu alan başka bir sekmede açık. Yazmak için diğer sekmeyi kapatıp bu sayfayı yenile.');return false;}
 if(blocked){notify('Mevcut kayıt okunamadı. Önce Yedek ve kurulum bölümünden ham kaydı indirip kurtarma işlemini tamamla.');return false;}
 try{validateEnvelope(next);if(localStorage.getItem(KEY)!==persistedRaw){blocked=true;throw Error('Kayıt başka bir sekmede değişti. Sayfayı yenile.');}const serialized=JSON.stringify(next);localStorage.setItem(KEY,serialized);persistedRaw=serialized;app=next;writable=true;$('#storage-status').textContent='Cihazda kaydedildi';return true;}
 catch(e){writable=false;$('#storage-status').textContent='Kaydedilemedi';notify('Kayıt saklanamadı; işlem uygulanmadı. Tarayıcı depolamasını kontrol et. '+e.message);return false;}
}
function updateState(next){return save({...app,[app.mode==='demo'?'demo':'personal']:next});}
function event(e){try{return updateState(C.addEvent(state(),e));}catch(err){notify('Kayıt eklenemedi: '+err.message);return false;}}
function exposure(t,mode){return event({id:uid(),type:'exposure',at:now(),objectiveId:t.objectiveId,taskId:t.id,familyId:t.familyId,taskVersion:t.version,sessionId:session.id,mode});}
function download(name,body,type='application/json'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function confirmAction(title,message){const d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-text').textContent=message;return new Promise(resolve=>{d.addEventListener('close',()=>resolve(d.returnValue==='ok'),{once:true});d.showModal();});}
function date(at){return new Date(at).toLocaleString('tr-TR',{dateStyle:'short',timeStyle:'short'});}
function modeBar(){return `<div class="mode-switch" role="group" aria-label="Çalışma alanı"><button data-mode="demo" aria-pressed="${app.mode==='demo'}">Örnek çalışma</button><button data-mode="personal" aria-pressed="${app.mode==='personal'}">Kendi hedeflerim</button></div>${app.mode==='demo'?'<div class="banner">Bu alandaki üç hedef tamamen kurgusaldır; tıbbi içerik değildir. Akışı deneyebilirsin. Kayıtları kendi çalışmalarına karışmaz.</div>':''}`;}
function header(title,desc){return `<div class="page-head"><div><div class="eyebrow">TUS YEREL / ${app.mode==='demo'?'ÖRNEK ALAN':'KİŞİSEL ALAN'}</div><h1>${title}</h1><p>${desc}</p></div></div>`;}
function go(next){if(session&&view==='study'&&next!=='study'){session=null;}view=next;render();$('#main').focus({preventScroll:true});}
function render(){
 document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view||(view==='study'&&b.dataset.view==='today')));
 $('#main').innerHTML=view==='study'?study():view==='library'?library():view==='records'?records():view==='backup'?backup():today();
 bind();
}
function today(){
 const s=C.summary(state(),coreTasks(),now()),p=makePlan();
 const total=p.reduce((sum,x)=>sum+x.task.estimatedMinutes,0);
 const reasons={retry_after_incorrect:'Önceki yanıt eksik kaldı',resolve_unknown:'İlk öğrenme için destek gerekli',new_objective:'Bu hedef için henüz yanıt yok',maintain_recall:'Yeni bir alıştırma / tekrar'};
 return header('Bugün neye çalışalım?','Zamanını seç. Küçük bir oturumla başlayabilir, istediğin yerde ara verebilirsin.')+modeBar()+`<div class="grid"><section><div class="panel focus"><h2>Bugünkü kapasitem</h2><p class="muted">Görev süreleri yaklaşık. Süre dolduğunda yeni soru açılmaz.</p><div class="time-options" role="group" aria-label="Çalışma süresi">${[0,5,15,30,60].map(m=>`<button data-minutes="${m}" aria-pressed="${state().settings.minutes===m}">${m===0?'Bugün ara':m+' dk'}</button>`).join('')}</div><div class="summary-line"><span>Bu oturumun önerisi</span><b>${p.length} görev · ≈ ${total} dk</b></div>${!p.length?`<p class="empty">${state().settings.minutes===0?'Bugün ara verebilirsin. Ara vermek yanlış yanıt veya başarısızlık kaydı oluşturmaz.':tasks().length?'Bu süreye sığan görev bulunamadı. Süreyi artırabilirsin.':'Henüz kendi sorun yok. Hedeflerim bölümünden kaynaklı bir soru ekle.'}</p>`:p.map((x,i)=>`<div class="task-row"><span class="number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(x.task.objectiveTitle)}</h3><p>${kinds[x.task.kind]} · ≈ ${x.task.estimatedMinutes} dk</p><p>${reasons[x.reason]||'Alıştırma'}</p></div></div>`).join('')}<div class="actions">${p.length?'<button class="primary full" id="start">Oturumu başlat</button>':'<button class="secondary full" data-goto="library">Hedeflere git</button>'}</div></div></section><section><div class="panel"><div class="eyebrow">GERÇEKLEŞEN ÇALIŞMA</div><h2>Şimdiye kadarki kayıtlar</h2><div class="stats"><div><span class="stat">${s.attempts.total}</span><small>Yanıt kaydı</small></div><div><span class="stat">${s.attempts.correct}</span><small>Doğru beyanı</small></div><div><span class="stat">${s.attempts.unknown}</span><small>Bilmiyorum</small></div></div><p class="small">Açıklamaya bakarak yaptığın öz değerlendirme, bağımsız sınav sonucu değildir.</p><button class="secondary full" data-goto="records">Kayıtları incele</button></div><div class="panel dark"><h2>Bir doğru, bütün hedef değildir.</h2><p>Hatırlama, açıklama ve ayırt etme yanıtlarını ayrı görebilirsin. Yeni soruyla gecikmeli kontrol, bu ilk sürümde henüz açık değil.</p><small>Aynı soruyu yeniden görmek “konu öğrenildi” puanı üretmez.</small></div></section></div>`;
}
function start(){const queue=makePlan().map(x=>x.task);if(!queue.length)return;session={id:uid(),queue,index:0,phase:'answer',answer:'',hintUsed:false,started:Date.now(),budget:state().settings.minutes*60000,completed:0,grades:[],locked:false};view='study';render();}
function study(){
 if(!session)return today();
 if(session.phase==='finished'){return header('Oturum burada tamamlandı.','Yanıtların kaydedildi. İstersen şimdi ara verebilirsin.')+`<div class="panel"><h2>${session.completed} görev üzerinde çalıştın</h2><p>${session.grades.filter(x=>x==='correct').length} doğru · ${session.grades.filter(x=>x==='incorrect').length} eksik / yanlış · ${session.grades.filter(x=>x==='unknown').length} bilmiyorum</p><div class="banner">Bunlar bu oturumdaki öz değerlendirmelerdir. Gecikmeli bağımsız öğrenme başarısı sayılmaz.</div><div class="actions"><button class="primary" data-goto="today">Çalışma masasına dön</button><button data-goto="records">Kayıtları gör</button></div></div>`;}
 const t=session.queue[session.index];
 return `<div class="page-head"><div><div class="eyebrow">${app.mode==='demo'?'KURGUSAL ÖRNEK':'KENDİ HEDEFİN'} · ${session.index+1} / ${session.queue.length}</div><h1>${esc(t.objectiveTitle)}</h1></div><button id="pause" class="secondary">Ara ver</button></div><div class="progress-track" aria-label="Oturum ilerlemesi"><span style="width:${session.index/session.queue.length*100}%"></span></div><div class="panel focus"><span class="pill">${kinds[t.kind]}</span><span class="pill">≈ ${t.estimatedMinutes} dk</span><p class="question">${esc(t.prompt)}</p>${session.phase==='answer'?`<label for="response">Yanıtın</label><textarea id="response" placeholder="Kendi cümlelerinle yaz…" maxlength="2000">${esc(session.answer)}</textarea>${session.hintUsed?`<div class="banner">${esc(t.hint||'Konuya ait belirleyici koşulu düşün.')}</div>`:''}<div class="actions"><button class="primary" id="reveal">Yanıtımı kontrol et</button><button id="unknown">Bilmiyorum, öğrenmek istiyorum</button>${session.hintUsed?'':'<button class="secondary" id="hint">İpucu</button>'}</div><p class="grade-note">Açıklama, yanıtını kilitledikten sonra görünür. Boş yanıt için “Bilmiyorum” seçeneğini kullan.</p>`:`<div class="small">Senin yanıtın</div><p class="answer">${esc(session.answer||'Bilmiyorum')}</p><div class="answer"><b>Beklenen yanıt / değerlendirme ölçütü</b><p>${esc(t.answer)}</p>${t.explanation?`<p>${esc(t.explanation)}</p>`:''}</div><p class="source"><b>Kaynak:</b> ${esc(t.source)}</p>${session.phase==='feedback'?`<h3>Yanıtını ölçütle karşılaştır</h3><div class="feedback-grid"><button class="primary" data-grade="correct">Doğru / yeterli</button><button data-grade="incorrect">Eksik / yanlış</button><button data-grade="unknown">Bilmiyordum</button></div><p class="grade-note">Bu bir öz değerlendirmedir. Açıklamanın gösterildiği ayrıca kaydedilir.</p>`:`<div class="banner">${session.lastGrade==='incorrect'?'Eksik kalan kısmı yukarıdaki açıklamayla karşılaştır. Bu düzeltme ayrı bir öğrenme adımıdır.':session.lastGrade==='unknown'?'İlk kez öğrenmek, unutmuş olmakla aynı şey değil. Kısa açıklamayı gözden geçir.':'Yanıtın kaydedildi. Daha sonra farklı bir soruyla kontrol etmek ayrıca gerekir.'}</div><div class="actions"><button class="primary" id="next">${session.index+1<session.queue.length?'Sıradaki görev':'Oturumu tamamla'}</button><button class="secondary" id="repair">Açıklamayı çalıştım</button></div>`}`}</div>`;
}
function library(){const cat=tasks();return header('Hedeflerim','Bir soruyu bir öğrenme hedefine bağla. Cevabı, değerlendirme ölçütünü ve kaynağı birlikte sakla.')+modeBar()+`<div class="panel">${app.mode==='personal'?'<button id="toggle-editor" class="primary">'+(editing?'Formu kapat':'Kaynaklı soru ekle')+'</button>':'<p class="muted">Örnek hedefler kurgusaldır. Kendi tıbbi sorularını eklemek için “Kendi hedeflerim” alanına geç.</p>'}${editing&&app.mode==='personal'?editor():''}${cat.length?cat.map(t=>`<div class="task-row"><div><h3>${esc(t.objectiveTitle)}</h3><span class="pill">${kinds[t.kind]}</span><span class="pill">${t.status==='synthetic'?'Kurgusal':'Kullanıcı onaylı'}</span><p>${esc(t.prompt)}</p><details><summary>Yanıtı ve kaynağı incele</summary><p>Yanıtı açmak maruziyet kaydı oluşturur.</p><button data-peek="${esc(t.id)}">Yanıtı aç</button><div id="peek-${esc(t.id)}"></div></details></div></div>`).join(''):'<p class="empty">İlk sorunu ekleyerek başlayabilirsin. Kendi kaynağından kısa ve net bir hedef seç.</p>'}</div>`;}
function editor(){return `<form id="card-form" class="card-form"><label for="objective">Öğrenme hedefi</label><input id="objective" name="objective" required maxlength="250" placeholder="Örn. Bir mekanizmayı neden–sonuç ilişkisiyle açıklamak"><div class="form-grid"><div><label for="kind">Soru türü</label><select id="kind" name="kind"><option value="recall">Hatırlama</option><option value="explain">Açıklama</option><option value="discriminate">Ayırt etme</option></select></div><div><label for="estimate">Tahmini süre (dakika)</label><input id="estimate" name="estimate" type="number" min="1" max="30" value="3" required></div></div><label for="prompt">Soru</label><textarea id="prompt" name="prompt" required maxlength="10000"></textarea><label for="answer">Beklenen yanıt / değerlendirme ölçütü</label><textarea id="answer" name="answer" required maxlength="10000"></textarea><label for="explanation">Kısa açıklama (isteğe bağlı)</label><textarea id="explanation" name="explanation" maxlength="10000"></textarea><label for="source">Kaynak ve sürümü / sayfası</label><input id="source" name="source" required maxlength="2000" placeholder="Kitap adı, baskı, sayfa veya kaynak bağlantısı"><label for="approval" class="check"><input id="approval" name="approval" type="checkbox" required><span>Soruyu, yanıtı ve kaynağı kendim kontrol ettim; kişisel çalışmamda kullanmayı onaylıyorum. Hasta bilgisi veya kullanım hakkım olmayan metin eklemiyorum.</span></label><div class="actions"><button class="primary" type="submit">Kontrol ettiğim soruyu kaydet</button></div><p class="small">Soru ekleme bir içerik incelemesidir; bu hedef için bağımsız başarı oluşturmaz. İlk sürümde kayıtlı sorular değiştirilmez; düzeltme için yeni soru eklenir.</p></form>`;}
function records(){const st=state(),s=C.summary(st,coreTasks(),now());const map=new Map(tasks().map(t=>[t.id,t]));const objectiveNames=new Map(tasks().map(t=>[t.objectiveId,t.objectiveTitle]));return header('Ne yaptım, ne gözledim?','Yanıtlar, açıklama gösterimleri ve çalışma beyanları birbirinden ayrı.')+modeBar()+`<div class="grid"><section><div class="panel"><h2>Görev türüne göre yanıtlar</h2>${Object.entries(kinds).map(([k,title])=>{const a=st.events.filter(e=>e.type==='attempt'&&e.kind===k);return `<div class="summary-line"><span>${title}</span><span>${a.filter(e=>e.result==='correct').length} doğru / ${a.length} yanıt</span></div>`;}).join('')}<p class="small">Doğru sayıları öz değerlendirmedir. Bu prototip bağımsız kontrol bankası ve yeterlik puanı sunmaz.</p></div><div class="panel"><h2>Son kayıtlar</h2>${st.events.length?st.events.slice(-60).reverse().map(e=>`<div class="record"><small>${date(e.at)} · ${e.type==='attempt'?kinds[e.kind]:e.type==='exposure'?'Karşılaşma kaydı':'Kullanıcı beyanı'}</small><p><b>${esc(map.get(e.taskId)?.objectiveTitle||objectiveNames.get(e.objectiveId)||'Hedef')}</b></p><p>${e.type==='attempt'?results[e.result]:e.type==='external'?'Dışarıda çalıştığını bildirdin; başarı sayılmadı.':({answer:'Yanıt / açıklama gösterildi',hint:'İpucu gösterildi',study:'Açıklamayı çalıştığını belirttin',practice:'Alıştırma gösterildi'}[e.mode])}</p>${e.type==='attempt'?`<p class="small">Yanıt: ${esc(e.answer||'—')}</p>`:''}</div>`).join(''):'<p class="empty">Henüz çalışma kaydı yok. Bir oturum tamamladığında burada görünür.</p>'}</div></section><section><div class="panel"><h2>Uygulama dışında çalıştım</h2><p class="small">Bu kayıt çalışma beyanıdır; soruya doğru yanıt verdiğin anlamına gelmez.</p>${tasks().length?`<form id="external-form"><label for="external-objective">Hedef</label><select id="external-objective">${[...new Map(tasks().map(t=>[t.objectiveId,t])).values()].map(t=>`<option value="${esc(t.objectiveId)}">${esc(t.objectiveTitle)}</option>`).join('')}</select><button class="secondary full" style="margin-top:18px">Çalışma beyanı ekle</button></form>`:'<p class="empty">Önce bir hedef ekle.</p>'}<p class="small" style="margin-top:18px">Toplam ${s.selfReports.total} beyan · ${s.exposures.total} karşılaşma</p></div></section></div>`;}
function backup(){return header('Yedeğin yanında olsun.','Tarayıcı verileri silinebilir. Cihaz değiştirmeden ve uygulamayı güncellemeden önce yedek indir.')+`<div class="grid"><section><div class="panel"><h2>Çalışmalarını dışa aktar</h2><p>Soruların, örnek ve kişisel çalışma kayıtların tek dosyada saklanır.</p><button class="primary" id="export">JSON yedeğini indir</button>${blocked?'<div class="banner warning" style="margin-top:16px">Mevcut kayıt okunamadığı için çalışma kapalı. Ham kaydı önce indir. Sağlam bir yedeği geri yükleyebilir veya aşağıdan kurtarma kopyası alarak yeni alan açabilirsin.</div><button id="raw-export">Okunamayan ham kaydı indir</button><button id="recover" class="danger">Kurtarma kopyasıyla yeni alan aç</button>':''}</div><div class="panel"><h2>Yedekten geri yükle</h2><p>Önce dosya tamamen kontrol edilir. Onayından sonra bu cihazdaki alan değiştirilir; önceki alanı geri alabilirsin.</p><label for="import-file">TUS JSON yedeği seç</label><input id="import-file" type="file" accept="application/json,.json"><div class="actions"><button id="undo-import">Son içe aktarmayı geri al</button></div></div></section><section><div class="panel"><h2>Android tablette açma</h2><p><b>Tek dosya:</b> İndirdiğin <code>TUS-Android-Prototip.html</code> dosyasını JavaScript çalıştırabilen bir tarayıcıda aç. Dosya önizleyicisi uygulamayı çalıştırmayabilir.</p><p><b>Daha güvenilir yol:</b> Paketi tablette bir klasöre çıkar ve Termux içinde o klasörde:</p><pre>python -m http.server 8000 --bind 127.0.0.1</pre><p>Tarayıcıda <code>http://localhost:8000/prototype/</code> adresini aç. İlk açılıştan sonra çevrimdışı önbellek durumunu burada kontrol et.</p><p id="offline-note" class="small">${location.protocol==='file:'?'Tek dosya modu: ağ kaynağı gerekmez; ana ekrana uygulama kurulumu bu modda yoktur.':'Çevrimdışı kabuk hazırlanıyor; tarayıcı desteği gerekir.'}</p><button id="install" ${deferredInstall?'':'hidden'}>Ana ekrana kur</button><details><summary>Bu sürümün sınırları</summary><p>APK değildir. Mac paketi, otomatik FSRS, tıbbi içerik bankası, soru düzeltme/göç sistemi, bağımsız kontrol ve cihazlar arası eşzamanlama sonraki işlerdir. Türkçe karakterler ve dokunma düzeni hedeflenmiştir; fiziksel Android cihaz testi bekler.</p><p>Oturumdan ayrılınca tamamlanan kayıtlar korunur; yazılmakta olan yanıt ve oturum sırası tutulmaz. Sayfa arka planda kalsa da oturum bütçesi geçer.</p></details></div></section></div>`;}
function bind(){
 document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(save({...app,mode:b.dataset.mode})){editing=false;session=null;render();}});
 document.querySelectorAll('[data-minutes]').forEach(b=>b.onclick=()=>{if(updateState({...state(),settings:{minutes:Number(b.dataset.minutes)}}))render();});
 $('#start')?.addEventListener('click',start);
 $('#toggle-editor')?.addEventListener('click',()=>{editing=!editing;render();});
 $('#card-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('approval')!=='on'){notify('Soruyu kaydetmek için kendi içerik kontrolünü onaylamalısın.');return;}const id='user-'+uid();const title=f.get('objective').trim();const existing=app.tasks.find(t=>t.objectiveTitle===title);const t={id,objectiveId:existing?.objectiveId||'objective-'+uid(),objectiveTitle:title,familyId:existing?.familyId||'family-'+uid(),kind:f.get('kind'),prompt:f.get('prompt').trim(),answer:f.get('answer').trim(),explanation:f.get('explanation').trim(),hint:'',bank:'training',status:'approved',estimatedMinutes:Number(f.get('estimate')),version:1,source:f.get('source').trim(),reviewedAt:now()};if(save({...app,tasks:[...app.tasks,t]})){editing=false;render();notify('Kontrol ettiğin soru kişisel alanına kaydedildi.');}});
 document.querySelectorAll('[data-peek]').forEach(b=>b.onclick=()=>{const t=tasks().find(x=>x.id===b.dataset.peek);const e={id:uid(),type:'exposure',at:now(),objectiveId:t.objectiveId,taskId:t.id,familyId:t.familyId,taskVersion:t.version,sessionId:'library-'+uid(),mode:'answer'};if(event(e)){$('#peek-'+CSS.escape(t.id)).innerHTML=`<div class="answer"><b>${esc(t.answer)}</b><p>${esc(t.explanation)}</p></div><p class="source">${esc(t.source)}</p>`;b.disabled=true;}});
 $('#response')?.addEventListener('input',e=>{session.answer=e.target.value;});
 $('#hint')?.addEventListener('click',()=>{if(exposure(session.queue[session.index],'hint')){session.hintUsed=true;render();}});
 $('#reveal')?.addEventListener('click',()=>{if(!session.answer.trim()){notify('Kısa bir yanıt yaz veya “Bilmiyorum” seçeneğini kullan.');return;}reveal(false);});
 $('#unknown')?.addEventListener('click',()=>reveal(true));
 document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>grade(b.dataset.grade));
 $('#repair')?.addEventListener('click',e=>{if(exposure(session.queue[session.index],'study')){e.target.textContent='Çalışma kaydı eklendi';e.target.disabled=true;}});
 $('#next')?.addEventListener('click',()=>{session.index++;if(session.index>=session.queue.length||Date.now()-session.started>=session.budget){session.phase='finished';}else{session.phase='answer';session.answer='';session.hintUsed=false;session.locked=false;}render();});
 $('#pause')?.addEventListener('click',async()=>{if(await confirmAction('Oturuma ara ver','Tamamlanan kayıtlar korunacak. Bu sorudaki yazılmamış veya değerlendirilmemiş yanıtın kaydedilmez.'))go('today');});
 $('#external-form')?.addEventListener('submit',e=>{e.preventDefault();if(event({id:uid(),type:'external',at:now(),objectiveId:$('#external-objective').value,source:'self_report',result:'unknown'}))render();});
 $('#export')?.addEventListener('click',()=>{if(blocked){notify('Sağlam veri yüklenmediği için boş yedek üretilmedi. Ham kaydı indir.');return;}download('TUS-yedek-'+new Date().toISOString().slice(0,10)+'.json',backupJSON(app));});
 $('#raw-export')?.addEventListener('click',()=>{try{download('TUS-ham-kurtarma.txt',localStorage.getItem(KEY)||'','text/plain');}catch(e){notify(e.message);}});
 $('#recover')?.addEventListener('click',async()=>{if(!writeAuthorized){notify('Kurtarma için diğer sekmeyi kapatıp sayfayı yenile.');return;}if(!await confirmAction('Kurtarma kopyasıyla yeni alan aç','Okunamayan veri cihazda ayrı bir kurtarma anahtarına kopyalanacak. Önce ham kaydı indirmen önerilir.'))return;try{const raw=localStorage.getItem(KEY);localStorage.setItem(KEY+'-recovery-'+Date.now(),raw||'');blocked=false;if(save(empty())){view='backup';render();notify('Eski ham veri kurtarma kopyasında korundu; yeni alan açıldı.');}else blocked=true;}catch(e){notify('Kurtarma kopyası alınamadı; eski veriye dokunulmadı. '+e.message);}});
 $('#import-file')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>MAX_BACKUP_BYTES)throw Error('Dosya 10 MB sınırını aşıyor.');const next=validateEnvelope(JSON.parse(await file.text()));if(!await confirmAction('Bu yedek geri yüklensin mi?',`${next.tasks.length} kişisel soru ve ${next.personal.events.length} kişisel kayıt bulundu. Mevcut alan değiştirilecek; önceki alanın kopyası korunacak.`))return;if(!writeAuthorized){notify('Bu alan başka sekmede açık. Diğer sekmeyi kapatıp sayfayı yenile.');return;}const oldUndo=localStorage.getItem(PREVIOUS);localStorage.setItem(PREVIOUS,localStorage.getItem(KEY)||JSON.stringify(app));const wasBlocked=blocked;blocked=false;if(save(next)){session=null;render();notify('Yedek geri yüklendi. Önceki alan için “geri al” seçeneği kullanılabilir.');}else{blocked=wasBlocked;try{if(oldUndo===null)localStorage.removeItem(PREVIOUS);else localStorage.setItem(PREVIOUS,oldUndo);}catch(restoreError){notify('Ana kayıt değişmedi; önceki geri alma kopyası kurtarılamadı. Ham yedek indir. '+restoreError.message);}}}catch(err){notify('Yedek yüklenmedi, mevcut kayıtlar korundu. '+err.message);}finally{e.target.value='';}});
 $('#undo-import')?.addEventListener('click',async()=>{try{const raw=localStorage.getItem(PREVIOUS);if(!raw)throw Error('Geri alınacak önceki alan bulunamadı.');const previous=validateEnvelope(JSON.parse(raw));if(!await confirmAction('Önceki alana dön','Şimdiki alan değiştirilecek. Gerekliyse önce yedeğini indir.'))return;const wasBlocked=blocked;blocked=false;if(save(previous)){localStorage.removeItem(PREVIOUS);session=null;render();notify('Önceki alan geri yüklendi.');}else blocked=wasBlocked;}catch(e){notify('Geri alma uygulanmadı. '+e.message);}});
 $('#install')?.addEventListener('click',async()=>{if(deferredInstall){await deferredInstall.prompt();deferredInstall=null;$('#install').hidden=true;}});
 updateOfflineNote();
}
function reveal(unknown){if(session.phase!=='answer')return;const t=session.queue[session.index];if(!exposure(t,'answer'))return;if(unknown){session.answer='';session.phase='feedback';grade('unknown');}else{session.phase='feedback';render();}}
function grade(result){if(session.phase!=='feedback'||session.locked)return;const t=session.queue[session.index];session.locked=true;const e={id:uid(),type:'attempt',at:now(),objectiveId:t.objectiveId,taskId:t.id,familyId:t.familyId,taskVersion:t.version,kind:t.kind,bank:t.bank,sessionId:session.id,result,answer:session.answer,hintUsed:session.hintUsed,answerShown:true,confidence:null};if(event(e)){session.completed++;session.grades.push(result);session.lastGrade=result;session.phase='graded';render();}else{session.locked=false;render();}}
let offlineText=location.protocol==='file:'?'Tek dosya modu: bütün çalışma kodu bu dosyada. Kalıcılık tarayıcı dosya izinlerine bağlıdır.':'Bu adres için çevrimdışı kurulum doğrulanmadı.';
function updateOfflineNote(){if($('#offline-note'))$('#offline-note').textContent=offlineText;}
function initialize(canWrite){
 writeAuthorized=canWrite;
 try{const raw=localStorage.getItem(KEY);persistedRaw=raw;if(raw)app=validateEnvelope(JSON.parse(raw));else if(canWrite){const serialized=JSON.stringify(app);localStorage.setItem(KEY,serialized);persistedRaw=serialized;} }catch(e){blocked=true;writable=false;view='backup';notify('Kayıt alanı açılamadı veya mevcut kayıt geçersiz. Veri otomatik silinmedi. '+e.message);$('#storage-status').textContent='Depolama kontrolü gerekli';}
 if(!canWrite){blocked=true;view='backup';notify('Bu alan başka bir sekmede açık veya yazma kilidi alınamadı. Yazmak için diğer sekmeyi kapatıp bu sayfayı yenile.');$('#storage-status').textContent='Salt okunur sekme';}
 render();
}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(session&&view==='study'){confirmAction('Çalışma ekranından ayrıl','Tamamlanan kayıtlar korunur; açık soru ve oturum sırası tutulmaz.').then(ok=>{if(ok)go(b.dataset.view);});}else go(b.dataset.view);});
$('.brand').onclick=e=>{e.preventDefault();if(!session)go('today');};
window.addEventListener('storage',e=>{if(e.key===KEY){blocked=true;session=null;notify('Kayıt başka bir sekmede değişti. Üzerine yazmamak için çalışma durduruldu; sayfayı yenile.');view='backup';render();}});
window.addEventListener('beforeunload',e=>{if(session&&session.phase!=='finished'){e.preventDefault();e.returnValue='';}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;if(view==='backup')render();});
if('serviceWorker'in navigator&&['http:','https:'].includes(location.protocol))navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{offlineText='Çevrimdışı kabuk kaydedildi. Aynı adresi interneti kapatıp yeniden açarak cihazında kontrol et.';updateOfflineNote();}).catch(()=>{offlineText='Çevrimdışı kurulum yapılamadı. Tek HTML dosyasını kullanabilir veya localhost üzerinden tekrar açabilirsin.';updateOfflineNote();});
if(navigator.locks?.request&&['http:','https:'].includes(location.protocol)){
 navigator.locks.request(KEY,{ifAvailable:true},async lock=>{initialize(Boolean(lock));if(lock)await new Promise(resolve=>window.addEventListener('pagehide',resolve,{once:true}));}).catch(()=>initialize(false));
}else initialize(true);
window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
// Test harness can inspect pure backup validation without bypassing UI approval.
globalThis.TusAppValidation={validateEnvelope,demoTasks,empty,MAX_BACKUP_BYTES,backupJSON};
})();
